// falsey value are those values which are considered as false  in a boolean context.

// false ,0, -0 , "" , null , undefined , NaN ,bigInt 0n are falsey values in js.

// " " ,"0", 'false' , [] , {} , function(){} are the truthy values in js.

// let userEmail = {};

// if (userEmail) {
//   console.log('User is verified');
// } else {
//   console.log('Please verify your email id');
// }

//to check arrays through this method.
// let myArr = [];
// if (myArr.length === 0) {
//   console.log(`this array is empty bro!`);
// }

//to check objects through this method.

// const myobj = {};

// if (Object.keys(myobj).length === 0) {
//   console.log('This object is Empty');
// }
